/* VERSÃO: 1.0.1 */

window.alert("ESSE SITE FOI FEITO SOB LICENÇA: GPLv2")
window.alert("ACESSE O CODIGO FONTE EM: https://github.com/otaviolm9/projeto-arte")
window.alert("NÃO RESPONSABILIZAMOS POR ERRO NA MAQUINA POR EFEITOS DESTE SITE")
window.alert("ESSE SITE ESTÁ EM PERIODO DE TESTES, MAL FUNCIONAMENTO E BUGS PODEM SER VISUALIZADOS")